# Generated by Django 3.1.7 on 2021-04-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photos',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
