# Generated by Django 3.1.7 on 2021-04-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_photo',
        ),
    ]
