# Generated by Django 3.1.7 on 2021-04-19 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210419_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
