# Generated by Django 3.1.7 on 2021-04-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_pictures_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
