# Generated by Django 3.1.7 on 2021-04-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
