# Generated by Django 3.1.7 on 2021-06-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='post_pictures',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
