# Generated by Django 3.1.7 on 2021-06-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210614_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_pictures',
        ),
    ]
